// @generated automatically by Diesel CLI.

diesel::table! {
    AmdProcessorList (id) {
        id -> Nullable<Integer>,
        model -> Nullable<Text>,
        family -> Nullable<Text>,
        line -> Nullable<Text>,
        platform -> Nullable<Text>,
        product_id_tray -> Nullable<Text>,
        product_id_boxed -> Nullable<Text>,
        product_id_mpk -> Nullable<Text>,
        launch_date -> Nullable<Text>,
        num_of_cpu_cores -> Nullable<Integer>,
        num_of_threads -> Nullable<Integer>,
        graphics_core_count -> Nullable<Text>,
        base_clock -> Nullable<Text>,
        max_boost_clock -> Nullable<Text>,
        all_core_boost_speed -> Nullable<Text>,
        l1_cache -> Nullable<Text>,
        l2_cache -> Nullable<Text>,
        l3_cache -> Nullable<Text>,
        ku_pricing -> Nullable<Text>,
        unlocked_for_overclocking -> Nullable<Text>,
        processor_technology_for_cpu_cores -> Nullable<Text>,
        cpu_socket -> Nullable<Text>,
        socket_count -> Nullable<Text>,
        pci_express_version -> Nullable<Text>,
        thermal_solution_pib -> Nullable<Text>,
        recommended_cooler -> Nullable<Text>,
        thermal_solution_mpk -> Nullable<Text>,
        default_tdp -> Nullable<Text>,
        amd_configurable_tdp_ctdp -> Nullable<Text>,
        max_operating_temperature_tjmax -> Nullable<Text>,
        os_support -> Nullable<Text>,
        system_memory_specification -> Nullable<Text>,
        system_memory_type -> Nullable<Text>,
        memory_channels -> Nullable<Integer>,
        per_socket_mem_bw -> Nullable<Text>,
        graphics_frequency -> Nullable<Text>,
        graphics_model -> Nullable<Text>,
        supported_technologies -> Nullable<Text>,
        workload_affinity -> Nullable<Text>,
        amd_ryzen_ai -> Nullable<Text>,
        fips_certification -> Nullable<Text>,
        fips_certification_links -> Nullable<Text>,
    }
}

diesel::table! {
    AmdProcessorsTypes (id) {
        id -> Nullable<Integer>,
        architecture -> Nullable<Text>,
        fabrication_nm -> Nullable<Text>,
        family -> Nullable<Text>,
        release_date -> Nullable<Text>,
        codename -> Nullable<Text>,
        model_group -> Nullable<Text>,
        cores -> Nullable<Text>,
        smt -> Nullable<Text>,
        clock_rate_mhz -> Nullable<Text>,
        bus_speed_type -> Nullable<Text>,
        cache_l1 -> Nullable<Text>,
        cache_l2 -> Nullable<Text>,
        cache_l3 -> Nullable<Text>,
        socket -> Nullable<Text>,
        memory_controller -> Nullable<Text>,
        simd -> Nullable<Text>,
        speed_power -> Nullable<Text>,
        other -> Nullable<Text>,
        changes -> Nullable<Text>,
    }
}

diesel::table! {
    IntelProcessorList (id) {
        id -> Nullable<Integer>,
        product_collection -> Nullable<Text>,
        vertical_segment -> Nullable<Text>,
        processor_number -> Nullable<Text>,
        lithography -> Nullable<Text>,
        use_conditions -> Nullable<Text>,
        recommended_customer_price -> Nullable<Text>,
        total_cores -> Nullable<Integer>,
        total_threads -> Nullable<Integer>,
        max_turbo_frequency -> Nullable<Text>,
        turbo_boost_technology_2_0_frequency -> Nullable<Text>,
        processor_base_frequency -> Nullable<Text>,
        cache -> Nullable<Text>,
        bus_speed -> Nullable<Text>,
        tdp -> Nullable<Text>,
        configurable_tdp_down_frequency -> Nullable<Text>,
        configurable_tdp_down -> Nullable<Text>,
        marketing_status -> Nullable<Text>,
        launch_date -> Nullable<Text>,
        embedded_options_available -> Nullable<Text>,
        included_items -> Nullable<Text>,
        description -> Nullable<Text>,
        functional_safety_documentation_available -> Nullable<Text>,
        servicing_status -> Nullable<Text>,
        end_of_servicing_updates_date -> Nullable<Text>,
        max_memory_size_dependent_on_memory_type -> Nullable<Text>,
        memory_types -> Nullable<Text>,
        max_num_of_memory_channels -> Nullable<Integer>,
        max_memory_bandwidth -> Nullable<Text>,
        ecc_memory_supported -> Nullable<Text>,
        processor_graphics -> Nullable<Text>,
        graphics_base_frequency -> Nullable<Text>,
        graphics_max_dynamic_frequency -> Nullable<Text>,
        graphics_video_max_memory -> Nullable<Text>,
        scalability -> Nullable<Text>,
        pci_express_revision -> Nullable<Text>,
        pci_express_configurations -> Nullable<Text>,
        max_num_of_pci_express_lanes -> Nullable<Text>,
        direct_media_interface_revision -> Nullable<Text>,
        max_num_of_dmi_lanes -> Nullable<Text>,
        intel_thunderbolt_4 -> Nullable<Text>,
        microprocessor_pcie_revision -> Nullable<Text>,
        chipset_pch_pcie_revision -> Nullable<Text>,
        sockets_supported -> Nullable<Text>,
        max_cpu_configuration -> Nullable<Text>,
        thermal_solution_specification -> Nullable<Text>,
        tjunction -> Nullable<Text>,
        package_size -> Nullable<Text>,
        intel_thermal_velocity_boost_temperature -> Nullable<Text>,
        operating_temperature_range -> Nullable<Text>,
        operating_temperature_maximum -> Nullable<Text>,
        operating_temperature_minimum -> Nullable<Text>,
        tcase -> Nullable<Text>,
        intel_optane_memory_supported -> Nullable<Text>,
        intel_turbo_boost_technology -> Nullable<Text>,
        intel_hyper_threading_technology -> Nullable<Text>,
        intel_aes_new_instructions -> Nullable<Text>,
        secure_key -> Nullable<Text>,
        intel_sg_extensions -> Nullable<Text>,
        intel_mp_extensions -> Nullable<Text>,
        intel_os_guard -> Nullable<Text>,
        intel_tx_technology -> Nullable<Text>,
        execute_disable_bit -> Nullable<Text>,
        intel_boot_guard -> Nullable<Text>,
        intel_stable_it_platform_program -> Nullable<Text>,
        intel_vt_technology -> Nullable<Text>,
        intel_vt_d -> Nullable<Text>,
        intel_vt_x_with_ept -> Nullable<Text>,
        intel_tdt -> Nullable<Text>,
        intel_amt -> Nullable<Text>,
        intel_ism -> Nullable<Text>,
        intel_one_click_recovery -> Nullable<Text>,
        intel_hardware_shield_eligibility -> Nullable<Text>,
        intel_cet -> Nullable<Text>,
        intel_total_memory_encryption_multi_key -> Nullable<Text>,
        intel_total_memory_encryption -> Nullable<Text>,
        mode_based_execute_control -> Nullable<Text>,
        intel_remote_platform_erase -> Nullable<Text>,
        intel_qas_acceleration -> Nullable<Text>,
        intel_vt_with_redirect_protection -> Nullable<Text>,
    }
}

diesel::table! {
    IntelProcessorsTypes (id) {
        id -> Nullable<Integer>,
        processor -> Nullable<Text>,
        series_nomenclature -> Nullable<Text>,
        codename -> Nullable<Text>,
        production_date -> Nullable<Text>,
        clock_rate -> Nullable<Text>,
        socket -> Nullable<Text>,
        fabrication_nm -> Nullable<Text>,
        tdp -> Nullable<Text>,
        cores -> Nullable<Text>,
        bus_speed -> Nullable<Text>,
        cache_l1 -> Nullable<Text>,
        cache_l2 -> Nullable<Text>,
        cache_l3 -> Nullable<Text>,
        overclock -> Nullable<Text>,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    AmdProcessorList,
    AmdProcessorsTypes,
    IntelProcessorList,
    IntelProcessorsTypes,
);
